name: flame_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flame: 0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/crate.png
   - assets/images/explosion-0.png
   - assets/images/explosion-1.png
   - assets/images/explosion-2.png
   - assets/images/explosion-3.png
   - assets/images/explosion-4.png
   - assets/images/explosion-5.png
   - assets/images/explosion-6.png
   - assets/audio/explosion.mp3
   - assets/audio/miss.mp3
   - assets/audio/music.ogg

  fonts:
   - family: Halo
     fonts:
      - asset: assets/fonts/halo.ttf