name: flame_crates_example
description: A very simple game showcasing the Flame Engine. Destroy the crates before they fall or loose points!

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
   - assets/images/crate.png
   - assets/images/explosion.png
   - assets/audio/explosion.mp3
   - assets/audio/miss.mp3
   - assets/audio/music.ogg

  fonts:
   - family: Halo
     fonts:
      - asset: assets/fonts/halo.ttf
